grafana/json-models/rms-global.json, grafana/json-models/standalone-global.json, omnistat/collector_smi.py, omnistat/collector_smi_v2.py
This PR updates a metric name:
`rocm_temperature_hbm_celsius -> rocm_temperature_memory_celsius`
and enables support for a vram sensor location.
Examples samples with the update:
```
rocm_temperature_hbm_celsius{card="1",location="hbm_0"} 47.0
rocm_temperature_celsius{card="7",location="junction"} 39.0
```
=> update name and query logic for memory temperature metric

docs/installation/user-mode.md, omnistat/config/omnistat.default, omnistat/config/omnistat.ornl, omnistat/omni_util.py, test/docker/slurm/omnistat-user.config
This PR addresses some issues with usermode options related to corebinding and SSH keys, and reorganizes usermode options under a single `[omnistat.usermode]` section.
Changes in corebinding:
- Remove default Prometheus binding on core 95.
- Make it possible to run without binding to any particular core when corebinding options are not set.
- Comment out corebinding by default.
New option for SSH keys:
- Introduce a new `ssh_key` option to customize the SSH key used to launching the exporters.
=> Fix usermode options

docs/grafana.md, grafana/json-models/rms-node.json, grafana/json-models/standalone-node.json
Change node dashboard instance variable to use capture groups and avoid the need for variables that point to other variables. This fixes an issue with older Grafana versions (tested with 10.x and 11.x), and removes the need for a user-defined variable (`omnistat_exporter_port`).
=> Fix node dashboard with older Grafana versions

omnistat-annotate, omnistat-monitor, omnistat-query, omnistat-rms-env, omnistat-standalone, omnistat-usermode
The check before loading `omnistat` modules with the `try/except` block is no longer necessary, and generally leads to confusing error messages.
For example, if one of the dependencies is missing, the current approach will only show the error message saying the `omnistat` module couldn't be loaded and asking to verify installation. After removing this check, Python will just fail to import the missing module, making it easier to understand what's going on.
=> Improve error message when loading omnistat modules

omnistat/collector_rms.py
The collector crashes when `squeue` times out since the `runShellCommand` with the `squeue` query returns `None`.
This PR ensures `squeue` isn't timing out before parsing the results by checking `data` is not `None`.
Not tested in production.
=> Skip data parsing when squeue times out

omnistat/node_monitoring.py
This PR makes sure the Omnistat endpoint generates responses with `text/plain` as content type in the HTTP headers, which is the correct value for a Prometheus endpoint.
By default, Flask responds with a `text/html` content type, which seems to break third-party tools that expect `text/plain`.
=> Make responses text/plain instead of text/html

docs/installation/user-mode.md, omnistat/query.py, requirements-query.txt
This PR introduces a new `--export` flag in `omnistat-query` to export time series as CSV for easier processing with external tools without relying on Prometheus/VictoriaMetrics and Grafana.
Optional tasks, to be decided if included in this PR or later:
=> Support for exporting data using omnistat-query

omnistat/omni_util.py, omnistat/query.py, omnistat/standalone.py
This PR modifies the push process slightly in user-mode when using VictoriaMetrics data store to include additional flush operations.  The changes address occasional issues observed for test jobs in a large supercomputing environment where collected telemetry was not immediately visible via a Prometheus query at the end of a very short job (e.g. 120 secs).
=> victoriametric tweaks to flush cache after backfilling data via push api

omnistat/omni_util.py
Introduces a verifyNumaCommand() support function that is used to verify supplied cpu core at runtime is available for use with `numactl` to satisfy #153.
=> introduce verifyNumaCommand() support function 

README.md, docs/grafana.md, docs/introduction.md, grafana/json-models/ras-summary.json, grafana/json-models/rms-node.json, omnistat/collector_smi.py, omnistat/collector_smi_v2.py, omnistat/config/omnistat.default, omnistat/monitor.py
This PR introduces additional gauge metrics within the SMI GPU data collectors to track error counts for specific GPU blocks (both correctable and uncorrectable).  
Examples of new metric definitions are highlighted below.
```
rocm_ras_umc_correctable_count{card="0"} 0.0
rocm_ras_umc_uncorrectable_count{card="0"} 0.0
rocm_ras_sdma_correctable_count{card="0"} 0.0
rocm_ras_sdma_uncorrectable_count{card="0"} 0.0
rocm_ras_gfx_correctable_count{card="0"} 0.0
rocm_ras_gfx_uncorrectable_count{card="0"} 0.0
rocm_ras_mmhub_correctable_count{card="0"} 0.0
rocm_ras_mmhub_uncorrectable_count{card="0"} 0.0
rocm_ras_pcie_bif_correctable_count{card="0"} 0.0
rocm_ras_pcie_bif_uncorrectable_count{card="0"} 0.0
rocm_ras_hdp_correctable_count{card="0"} 0.0
rocm_ras_hdp_uncorrectable_count{card="0"} 0.0
``` …
=> include metrics tracking error counts for a GPU block

.github/workflows/formatting.yml, .github/workflows/test-user-pull.yml, .github/workflows/test-user-push.yml, .github/workflows/test.yml
Ubuntu 20.04 deprecated as of 2025/04/15.
=> Update formatting actions to newer Ubuntu

README.md, docs/introduction.md, omnistat/collector_network.py, omnistat/config/omnistat.default, omnistat/monitor.py
Support network metrics based on sysfs data. 
Remaining tasks:
=> Collect network metrics

README.md, docs/introduction.md, omnistat/collector_smi.py, omnistat/collector_smi_v2.py, omnistat/monitor.py, omnistat/standalone.py
This PR adds two new functionalities:
New (optional) metrics to track current power cap settings in watts. Example metrics from MI300X are highlighted as follows:
```
rocm_power_cap_watts{card="3"} 1000.0
rocm_power_cap_watts{card="2"} 1000.0
rocm_power_cap_watts{card="0"} 1000.0
rocm_power_cap_watts{card="5"} 1000.0
rocm_power_cap_watts{card="7"} 1000.0
rocm_power_cap_watts{card="6"} 1000.0
rocm_power_cap_watts{card="4"} 1000.0
```
These metrics can be enabled via the following runtime option:
```
[omnistat.collectors]
enable_power_cap = True
```
This new metric addition applies to both system and user-mode usage.
------
Add ability to supply application figure-of-merit (FOM) data to Omnistat during **user-mode** execution.  This allows applications to provide their own application …
=> add metric to track power-cap settings and user-supplied figure-of-merit

omnistat/collector_rocprofiler.py, omnistat/monitor.py
This is an alternative approach to #12. While I think the python module for rocprofiler device mode in #12 is something that can be potentially useful beyond this project, dealing with its building and installation is more complex and not as convenient as everything else we have in Omnistat.
The implementation in this PR is based on ctypes and is 1) simpler, 2) similar to our other collectors, 3) good enough in terms of performance.
I'll be using this approach for prototyping, and we can discuss future plans later.
=> Alternative counter collection with rocprofiler

omnistat/config/omnistat.default, omnistat/omni_util.py, omnistat/standalone.py
This PR adds the capability to push data directly to an external victoria-metrics server while collecting telemetry in user-mode (as opposed to spinning up a temporary instance local to the cluster).  The requirements to use this feature assume:
1. all compute nodes participating in the user-mode collection can route outward to the server (either directly or via an http_proxy)
2. victoria-metrics server networking configured to allow incoming requests from compute node IPs (or proxy) on assigned port
Additional runtime options  to enable and control this mode of operation are highlighted as follows:
```
[omnistat.usermode]
external_victoria = True
external_victoria_endpoint = victoria.endpoint.org
external_victoria_port = 8440
```
=> add ability to push directly to remote victoria-metrics instance in user-mode sampling

docs/installation/user-mode.md, omnistat/query.py
Changes the behavior of the `--export` flag. Instead of a required path to a CSV file to be exported, `--export` is now meant to point to a directory (existing or new). If no export argument is provided, the export directory will be the current directory.
Tasks:
=> Support for exporting all metrics

omnistat/collector_smi_v2.py
Simple fix for the amdsmi collector, which is currently failing because it's attempting to use a variable that hasn't been set.
```
[2025-06-27 14:18:03 -0500] [3777380] [INFO] Starting gunicorn 21.2.0                                                                                           [2025-06-27 14:18:03 -0500] [3777380] [INFO] Listening at: http://0.0.0.0:8088 (3777380)
[2025-06-27 14:18:03 -0500] [3777380] [INFO] Using worker: sync
[2025-06-27 14:18:03 -0500] [3777383] [INFO] Booting worker with pid: 3777383
[2025-06-27 14:18:03 -0500] [3777383] [ERROR] Exception in worker process
Traceback (most recent call last):
File "gunicorn/arbiter.py", line 608, in spawn_worker
self.cfg.post_fork(self, worker)
File "omnistat/node_monitoring.py", line 95, in post_fork
monitor.initMetrics() …
```
=> Fix variable in amdsmi collector

docs/installation/user-mode.md, omnistat/collector_pm_counters.py, omnistat/collector_rms.py, omnistat/monitor.py, omnistat/query.py, test/test_query.py
This data collector enables vendor-provided metrics based on files populated in `/sys/cray/pm_counters` on HPE Cray supercomputing environments.  These include node-level and individual accelerator (GPU) telemetry values. Example omnistat counter examples highlighted below:
```
omnistat_vendor_energy_joules{vendor="cray"} 2.178501771e+09
omnistat_vendor_accel_energy_joules{card="0",vendor="cray"} 4.79512261e+08
omnistat_vendor_accel_energy_joules{card="1",vendor="cray"} 4.86017852e+08
omnistat_vendor_accel_energy_joules{card="2",vendor="cray"} 4.84580288e+08
omnistat_vendor_accel_energy_joules{card="3",vendor="cray"} 4.74312657e+08
omnistat_vendor_accel_power_watts{card="3",vendor="cray"} 104.0
omnistat_vendor_accel_power_watts{card="0",vendor="cray"} 103.0 …
```
=> Add new (optional) data collector to pull in power management counters 

docker/grafana/json-models/job.json, grafana/json-models/system/rms-job.json, grafana/source/job.json, omnistat/collector_smi.py, omnistat/collector_smi_v2.py, omnistat/monitor.py, omnistat/utils.py
This PR introduces per-GPU CU occupancy metrics. It relies on files generated on for each process by the driver under `/sys/class/kfd/kfd/proc/{PID}/stats_{GUID}/cu_occupancy`.
These `cu_occupancy` files report the number of compute units that are occupied for any given process and GPU. It takes the number of waves in-flight and translates them into a number of compute units based on the maximum number of waves per CU. Reference: https://github.com/ROCm/ROCK-Kernel-Driver/blob/ceb12c04e2b5b53ec0779362831f5ee40c4921e4/drivers/gpu/drm/amd/amdkfd/kfd_process.c#L257-L326
Two additional metrics have been added as part of this PR:
- `rocm_num_compute_units`: Total number of CUs per GPU (static).
- `rocm_compute_unit_occupancy`: CU occupancy per GPU, aggregating CU occupancy from all processes. …
=> Track CU Occupancy

docker/grafana/json-models/job.json, grafana/Makefile, grafana/json-models/system/rms-job.json, grafana/source/job.json
=> Fix and improve dashboards

omnistat/query.py
This PR enables selection of specific annotation markers with the query tool.
Existing job/jobstep queries remain unchanged, but when the `--marker` flag is set, the tool will perform an additional query to find an annotation with the given marker text and update the time range accordingly. If the given marker can't be found, execution will end early with an error.
Sample report with marker:
```
----------------------------------------------------------------------
Omnistat Report Card for Job Id: 3566994
** Report confined to annotation marker=sample marker
----------------------------------------------------------------------
Job Overview (Num Nodes = 1, Machine = Test System)
--> Start time = 2025-07-10 10:31:19
--> End   time = 2025-07-10 10:34:00
--> Duration   = 160 secs
GPU …
```
=> Support querying annotation markers

docs/metrics.md, grafana/json-models/system/rms-global.json, grafana/json-models/system/standalone-global.json, grafana/source/global.json, omnistat/collector_smi_v2.py, omnistat/monitor.py
Initial implementation to track encoder/decoder utilization. It looks like only decoder utilization is currently supported by amd-smi, and it only works with MI3xx.
Decoder utilization is measured using `vcn_activity`, which reports 4 utilization values. The amd-smi CLI averages the 4 values to provide an aggregated decoder utilization. We can follow the same approach, but for now this PR keeps track of each engine with a different label:
```
rocm_decoder_utilization_percentage{card="0",engine="0"} 0.0
rocm_decoder_utilization_percentage{card="0",engine="1"} 0.0
rocm_decoder_utilization_percentage{card="0",engine="2"} 0.0
rocm_decoder_utilization_percentage{card="0",engine="3"} 0.0
```
Tasks / To be decided:
Observations:
- It's still unclear how encoder utilization will be supported in …
=> Track decoder utilization

docs/sites.md, omnistat/collector_pm_counters.py, omnistat/query.py
=> Update vendor labels and document vendor metrics

pyproject.toml
Removing the requirement for Python <3.11. There used to be some issues with Python 3.11/3.12 and some of Omnistat's dependencies, but everything seems to be working as expected now.
=> Remove max Python version requirement
